#!/bin/sh

cat <<EOF >> .env
SECRET_KEY=$SECRET_KEY
DB_NAME=$DB_NAME
DB_USER=$PB_USER
DB_PASS=$DB_PASS
DB_HOST=$DB_HOST
DJANGO_DEBUG=True
GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS
ALLOW_TRANSLATION_IMPORT=True
EOF

echo "alias fly='flyctl'" >> ~/.bashrc
echo "alias fly='flyctl'" >> ~/.zshrc
